name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fix permissions for Gemfile.lock
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder:latest /bin/bash -c "chmod 666 /srv/jekyll/Gemfile.lock"
    - name: Install Bootstrap
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder:latest /bin/bash -c "cd /srv/jekyll && npm install bootstrap"
    - name: Install correct Bundler version
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder:latest /bin/bash -c "gem install bundler && bundle install"
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Fix permissions for Gemfile.lock
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder:latest /bin/bash -c "chmod 666 /srv/jekyll/Gemfile.lock"
    - name: Install Bootstrap
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        jekyll/builder:latest /bin/bash -c "cd /srv/jekyll && npm install bootstrap"
